### PR TITLE
Prepare for staging environment for master and client nodes.

### PR DESCRIPTION
**Pull request by johanherman**
NOT adapted for the new Stackstorm version as of yet

### CODE REVIEW

**Comment by johandahlberg** [comment]
Not merging.

**Comment by johandahlberg** [comment]
@johanherman Will you have a look at this?

**Comment by johanherman** [comment]
Yes, it will be fixed when I have switched over to 0.13.2.

**Comment by johandahlberg** [comment]
Great!

**Comment by johanherman** [comment]
Should merge now.

**Comment by johandahlberg** [comment]
Looks good!

**Pull request merged**
